### ISSUE TITLE
配置文件关闭actuator, 但是他的controller注册了，这关闭有啥用？

### ISSUE THREAD

**Issue by twdp** [hidevopsio/hiboot#108]
在配置文件中profiles.include列表中删除, 提示已经被过滤掉，但是他的controller /health依然会注册进来。

[WARN] 2020/02/26 17:08 Auto configuration actuator is filtered out! Just ignore this warning if you intended to do so.
[INFO] 2020/02/26 17:08 Auto configuration logging is configured on logging.configuration.
[INFO] 2020/02/26 17:08 Mapped GET "/health" onto actuator.healthController.Get()

**Comment by john-deng** [comment]
@twdp 需要配合开关使用 app.profiles.filter: true

**Comment by john-deng** [comment]
@twdp 谢谢，你可以提交PR
