### ISSUE TITLE
application-local.yml 不能覆盖原本的环境变量

### ISSUE THREAD

**Issue by ClareChu** [hidevopsio/hiboot#51]
**Describe the bug**
{{ Succinctly describe the bug }}
我的环境变量 为local
The following profiles are active: local, [jwt grpc etcd kube mio locale docker websocket gorm bolt web]
![image](https://user-images.githubusercontent.com/28973013/48944122-75612600-ef60-11e8-8a09-1de924203521.png)
我想覆盖默认的环境配置，但是并没有覆盖掉原来的值
**Expected behavior**
{{ What did you expect to happen? }}
我需要application-local.yml 覆盖application-gorm.yml 里面的host参数，来调节不通的环境。

**Steps to reproduce the bug**
{{ Minimal steps to reproduce the behavior }}

**Version**
{{ What version of Hiboot are you using? }}
v0.11.0
**Environment**
{{ Which environment, cloud vendor, OS, etc are you using? }}
macos 10.13

**Comment by john-deng** [comment]
reproduced this bug and it will be fixed on next release

**Comment by john-deng** [comment]
@ClareChu this issue is solved on v0.11.1
